INSERT INTO pools_typeofbds (TypeName) VALUES ('Căn Hộ Chung Cư'), ('Nhà Mặt Phố'), ('Nhà Đất Thổ Cư'), ('Nhà Biệt Thự, Liền Kề'), ('Nhà Trọ, Phòng Trọ'), ('Nhà Xưởng, Mặt Bằng, Kho Bãi'), ('Đất Trang Trại'), ('Nhà Trong Ngõ'), ('Đất Nông Nghiệp, Đất Vườn'), ('Đất Nền Dự Án'), ('Đất Dịch Vụ, Đền Bù'), ('Văn Phòng, TTTM, Cửa Hàng, Kiot'), ('Nhà Hàng, Khách Sạn, Resort'), ('Condotel'), ('ShopHouse'), ('OfficeTel');

INSERT INTO pools_address (district, province_city) VALUES 
('Ba Đình', 'Hà Nội'), ('Hoàn Kiếm', 'Hà Nội'), ('Tây Hồ', 'Hà Nội'), ('Long Biên', 'Hà Nội'), ('Cầu Giấy', 'Hà Nội'), ('Đống Đa', 'Hà Nội'), ('Hai Bà Trưng', 'Hà Nội'), ('Hoàng Mai', 'Hà Nội'), ('Thanh Xuân', 'Hà Nội'), ('Sóc Sơn', 'Hà Nội'), ('Đông Anh', 'Hà Nội'), ('Gia Lâm', 'Hà Nội'), ('Nam Từ Liêm', 'Hà Nội'), ('Thanh Trì', 'Hà Nội'), ('Bắc Từ Liêm', 'Hà Nội'), ('Mê Linh', 'Hà Nội'), ('Hà Đông', 'Hà Nội'), ('Sơn Tây', 'Hà Nội'), ('Ba Vì', 'Hà Nội'), ('Phúc Thọ', 'Hà Nội'), ('Đan Phượng', 'Hà Nội'), ('Hoài Đức', 'Hà Nội'), ('Quốc Oai', 'Hà Nội'), ('Thạch Thất', 'Hà Nội'), ('Chương Mỹ', 'Hà Nội'), ('Thanh Oai', 'Hà Nội'), ('Thường Tín', 'Hà Nội'), ('Phú Xuyên', 'Hà Nội'), ('Ứng Hòa', 'Hà Nội'), ('Mỹ Đức', 'Hà Nội'),
('9', 'Hồ Chí Minh'),('1', 'Hồ Chí Minh'), ('12', 'Hồ Chí Minh'), ('Gò Vấp', 'Hồ Chí Minh'), ('Bình Thạnh', 'Hồ Chí Minh'), ('Tân Bình', 'Hồ Chí Minh'), ('Tân Phú', 'Hồ Chí Minh'), ('Phú Nhuận', 'Hồ Chí Minh'), ('Thủ Đức', 'Hồ Chí Minh'), ('3', 'Hồ Chí Minh'), ('10', 'Hồ Chí Minh'), ('11', 'Hồ Chí Minh'), ('4', 'Hồ Chí Minh'), ('5', 'Hồ Chí Minh'), ('6', 'Hồ Chí Minh'), ('8', 'Hồ Chí Minh'), ('Bình Tân', 'Hồ Chí Minh'), ('7', 'Hồ Chí Minh'), ('Củ Chi', 'Hồ Chí Minh'), ('Hóc Môn', 'Hồ Chí Minh'), ('Bình Chánh', 'Hồ Chí Minh'), ('Nhà Bè', 'Hồ Chí Minh'), ('Cần Giờ', 'Hồ Chí Minh'),
('Hồng Bàng', 'Hải Phòng'), ('Ngô Quyền', 'Hải Phòng'), ('Lê Chân', 'Hải Phòng'), ('Hải An', 'Hải Phòng'), ('Kiến An', 'Hải Phòng'), ('Đồ Sơn', 'Hải Phòng'), ('Dương Kinh', 'Hải Phòng'), ('Thuỷ Nguyên', 'Hải Phòng'), ('An Dương', 'Hải Phòng'), ('An Lão', 'Hải Phòng'), ('Kiến Thuỵ', 'Hải Phòng'), ('Tiên Lãng', 'Hải Phòng'), ('Vĩnh Bảo', 'Hải Phòng'), ('Cát Hải', 'Hải Phòng'), ('Bạch Long Vĩ', 'Hải Phòng'),
('Liên Chiểu', 'Đà Nẵng'), ('Thanh Khê', 'Đà Nẵng'), ('Hải Châu', 'Đà Nẵng'), ('Sơn Trà', 'Đà Nẵng'), ('Ngũ Hành Sơn', 'Đà Nẵng'), ('Cẩm Lệ', 'Đà Nẵng'), ('Hòa Vang', 'Đà Nẵng'),
('Ninh Kiều', 'Cần Thơ'), ('Ô Môn', 'Cần Thơ'), ('Bình Thuỷ', 'Cần Thơ'), ('Cái Răng', 'Cần Thơ'), ('Thốt Nốt', 'Cần Thơ'), ('Cờ Đỏ', 'Cần Thơ'), ('Thới Lai', 'Cần Thơ'),
('Long Xuyên', 'An Giang'), ('Châu Đốc', 'An Giang'), ('An Phú', 'An Giang'), ('Tân Châu', 'An Giang'), ('Phú Tân', 'An Giang'), ('Châu Phú', 'An Giang'), ('Tịnh Biên', 'An Giang'), ('Tri Tôn', 'An Giang'), ('Thoại Sơn', 'An Giang'),
('Vũng Tàu', 'Bà Rịa – Vũng Tàu'), ('Bà Rịa', 'Bà Rịa – Vũng Tàu'), ('Châu Đức', 'Bà Rịa – Vũng Tàu'), ('Xuyên Mộc', 'Bà Rịa – Vũng Tàu'), ('Long Điền', 'Bà Rịa – Vũng Tàu'), ('Đất Đỏ', 'Bà Rịa – Vũng Tàu'), ('Phú Mỹ', 'Bà Rịa – Vũng Tàu'), ('Côn Đảo', 'Bà Rịa – Vũng Tàu'),
('Bạc Liêu', 'Bạc Liêu'), ('Hồng Dân', 'Bạc Liêu'), ('Phước Long', 'Bạc Liêu'), ('Vĩnh Lợi', 'Bạc Liêu'), ('Giá Rai', 'Bạc Liêu'), ('Đông Hải', 'Bạc Liêu'), ('Hoà Bình', 'Bạc Liêu');

INSERT INTO pools_address (district, province_city) VALUES ('Bắc Giang', 'Bắc Giang'),('Yên Thế', 'Bắc Giang'),('Tân Yên', 'Bắc Giang'),('Lạng Giang', 'Bắc Giang'),('Lục Nam', 'Bắc Giang'),('Lục Ngạn', 'Bắc Giang'),('Sơn Động', 'Bắc Giang'),('Yên Dũng', 'Bắc Giang'),('Việt Yên', 'Bắc Giang'),('Hiệp Hòa', 'Bắc Giang');
INSERT INTO pools_address (district, province_city) VALUES ('Bắc Kạn', 'Bắc Kạn'),('Pác Nặm', 'Bắc Kạn'),('Ba Bể', 'Bắc Kạn'),('Ngân Sơn', 'Bắc Kạn'),('Bạch Thông', 'Bắc Kạn'),('Chợ Đồn', 'Bắc Kạn'),('Chợ Mới', 'Bắc Kạn'),('Na Rì', 'Bắc Kạn');
INSERT INTO pools_address (district, province_city) VALUES ('Bắc Ninh', 'Bắc Ninh'),('Yên Phong', 'Bắc Ninh'),('Quế Võ', 'Bắc Ninh'),('Tiên Du', 'Bắc Ninh'),('Từ Sơn', 'Bắc Ninh'),('Thuận Thành', 'Bắc Ninh'),('Gia Bình', 'Bắc Ninh'),('Lương Tài', 'Bắc Ninh');
INSERT INTO pools_address (district, province_city) VALUES ('Bến Tre', 'Bến Tre'),('Chợ Lách', 'Bến Tre'),('Mỏ Cày Nam', 'Bến Tre'),('Giồng Trôm', 'Bến Tre'),('Bình Đại', 'Bến Tre'),('Ba Tri', 'Bến Tre'),('Thạnh Phú', 'Bến Tre'),('Mỏ Cày Bắc', 'Bến Tre');
INSERT INTO pools_address (district, province_city) VALUES ('Thủ Dầu Một', 'Bình Dương'),('Bàu Bàng', 'Bình Dương'),('Dầu Tiếng', 'Bình Dương'),('Bến Cát', 'Bình Dương'),('Phú Giáo', 'Bình Dương'),('Tân Uyên', 'Bình Dương'),('Dĩ An', 'Bình Dương'),('Thuận An', 'Bình Dương'),('Bắc Tân Uyên', 'Bình Dương');
INSERT INTO pools_address (district, province_city) VALUES ('Quy Nhơn', 'Bình Định'),('Hoài Nhơn', 'Bình Định'),('Hoài Ân', 'Bình Định'),('Phù Mỹ', 'Bình Định'),('Vĩnh Thạnh', 'Bình Định'),('Tây Sơn', 'Bình Định'),('Phù Cát', 'Bình Định'),('An Nhơn', 'Bình Định'),('Tuy Phước', 'Bình Định'),('Vân Canh', 'Bình Định');
INSERT INTO pools_address (district, province_city) VALUES ('Phước Long', 'Bình Phước'), ('Đồng Xoài', 'Bình Phước'), ('Bình Long', 'Bình Phước'), ('Bù Gia Mập', 'Bình Phước'), ('Lộc Ninh', 'Bình Phước'), ('Bù Đốp', 'Bình Phước'), ('Hớn Quản', 'Bình Phước'), ('Đồng Phú', 'Bình Phước'), ('Bù Đăng', 'Bình Phước'), ('Chơn Thành', 'Bình Phước'), ('Phú Riềng', 'Bình Phước');
INSERT INTO pools_address (district, province_city) VALUES ('Phan Thiết', 'Bình Thuận'), ('La Gi', 'Bình Thuận'), ('Tuy Phong', 'Bình Thuận'), ('Bắc Bình', 'Bình Thuận'), ('Hàm Thuận Bắc', 'Bình Thuận'), ('Hàm Thuận Nam', 'Bình Thuận'), ('Tánh Linh', 'Bình Thuận'), ('Đức Linh', 'Bình Thuận'), ('Hàm Tân', 'Bình Thuận'), ('Phú Quí', 'Bình Thuận');
INSERT INTO pools_address (district, province_city) VALUES ('Cà Mau', 'Cà Mau'), ('U Minh', 'Cà Mau'), ('Thới Bình', 'Cà Mau'), ('Trần Văn Thời', 'Cà Mau'), ('Cái Nước', 'Cà Mau'), ('Đầm Dơi', 'Cà Mau'), ('Năm Căn', 'Cà Mau'), ('Ngọc Hiển', 'Cà Mau');

INSERT INTO pools_address (district, province_city) VALUES ('Cao Bằng', 'Cao Bằng'), ('Bảo Lâm', 'Cao Bằng'), ('Bảo Lạc', 'Cao Bằng'), ('Hà Quảng', 'Cao Bằng'), ('Trùng Khánh', 'Cao Bằng'), ('Hạ Lang', 'Cao Bằng'), ('Quảng Hòa', 'Cao Bằng'), ('Hoà An', 'Cao Bằng'), ('Nguyên Bình', 'Cao Bằng'), ('Thạch An', 'Cao Bằng');
INSERT INTO pools_address (district, province_city) VALUES ('Buôn Ma Thuột', 'Đắk Lắk'), ('Buôn Hồ', 'Đắk Lắk'), ('Ea H\'leo', 'Đắk Lắk'), ('Ea Súp', 'Đắk Lắk'), ('Buôn Đôn', 'Đắk Lắk'), ('Cư M\'gar', 'Đắk Lắk'), ('Krông Búk', 'Đắk Lắk'), ('Krông Năng', 'Đắk Lắk'), ('Ea Kar', 'Đắk Lắk'), ('M\'Đrắk', 'Đắk Lắk'), ('Krông Bông', 'Đắk Lắk'), ('Krông Pắc', 'Đắk Lắk'), ('Krông A Na', 'Đắk Lắk'), ('Lắk', 'Đắk Lắk'), ('Cư Kuin', 'Đắk Lắk');

INSERT INTO pools_address (district, province_city) VALUES ('Gia Nghĩa', 'Đắk Nông'), ('Đăk Glong', 'Đắk Nông'), ('Cư Jút', 'Đắk Nông'), ('Đắk Mil', 'Đắk Nông'), ('Krông Nô', 'Đắk Nông'), ('Đắk Song', 'Đắk Nông'), ('Đắk R\'Lấp', 'Đắk Nông'), ('Tuy Đức', 'Đắk Nông');
INSERT INTO pools_address (district, province_city) VALUES ('Biên Hòa', 'Đồng Nai'), ('Long Khánh', 'Đồng Nai'), ('Tân Phú', 'Đồng Nai'), ('Vĩnh Cửu', 'Đồng Nai'), ('Định Quán', 'Đồng Nai'), ('Trảng Bom', 'Đồng Nai'), ('Thống Nhất', 'Đồng Nai'), ('Cẩm Mỹ', 'Đồng Nai'), ('Long Thành', 'Đồng Nai'), ('Xuân Lộc', 'Đồng Nai'), ('Nhơn Trạch', 'Đồng Nai');
INSERT INTO pools_address (district, province_city) VALUES ('Cao Lãnh', 'Đồng Tháp'), ('Sa Đéc', 'Đồng Tháp'), ('Hồng Ngự', 'Đồng Tháp'), ('Tân Hồng', 'Đồng Tháp'), ('Hồng Ngự', 'Đồng Tháp'), ('Tháp Mười', 'Đồng Tháp'), ('Cao Lãnh', 'Đồng Tháp'), ('Thanh Bình', 'Đồng Tháp'), ('Lấp Vò', 'Đồng Tháp'), ('Lai Vung', 'Đồng Tháp');
INSERT INTO pools_address (district, province_city) VALUES ('Pleiku', 'Gia Lai'), ('An Khê', 'Gia Lai'), ('Ayun Pa', 'Gia Lai'), ('KBang', 'Gia Lai'), ('Đăk Đoa', 'Gia Lai'), ('Chư Păh', 'Gia Lai'), ('Ia Grai', 'Gia Lai'), ('Mang Yang', 'Gia Lai'), ('Kông Chro', 'Gia Lai'), ('Đức Cơ', 'Gia Lai'), ('Chư Prông', 'Gia Lai'), ('Chư Sê', 'Gia Lai'), ('Đăk Pơ', 'Gia Lai'), ('Ia Pa', 'Gia Lai'), ('Krông Pa', 'Gia Lai'), ('Phú Thiện', 'Gia Lai'), ('Chư Pưh', 'Gia Lai');
INSERT INTO pools_address (district, province_city) VALUES ('Hà Giang', 'Hà Giang'), ('Đồng Văn', 'Hà Giang'), ('Mèo Vạc', 'Hà Giang'), ('Yên Minh', 'Hà Giang'), ('Quản Bạ', 'Hà Giang'), ('Vị Xuyên', 'Hà Giang'), ('Bắc Mê', 'Hà Giang'), ('Hoàng Su Phì', 'Hà Giang'), ('Xín Mần', 'Hà Giang'), ('Bắc Quang', 'Hà Giang'), ('Quang Bình', 'Hà Giang');
INSERT INTO pools_address (district, province_city) VALUES ('Phủ Lý', 'Hà Nam'), ('Duy Tiên', 'Hà Nam'), ('Kim Bảng', 'Hà Nam'), ('Thanh Liêm', 'Hà Nam'), ('Bình Lục', 'Hà Nam'), ('Lý Nhân', 'Hà Nam');
INSERT INTO pools_address (district, province_city) VALUES ('Hà Tĩnh', 'Hà Tĩnh'), ('Hồng Lĩnh', 'Hà Tĩnh'), ('Hương Sơn', 'Hà Tĩnh'), ('Đức Thọ', 'Hà Tĩnh'), ('Vũ Quang', 'Hà Tĩnh'), ('Nghi Xuân', 'Hà Tĩnh'), ('Can Lộc', 'Hà Tĩnh'), ('Hương Khê', 'Hà Tĩnh'), ('Thạch Hà', 'Hà Tĩnh'), ('Cẩm Xuyên', 'Hà Tĩnh'), ('Kỳ Anh', 'Hà Tĩnh'), ('Lộc Hà', 'Hà Tĩnh'), ('Kỳ Anh', 'Hà Tĩnh');
INSERT INTO pools_address (district, province_city) VALUES ('Hải Dương', 'Hải Dương'), ('Chí Linh', 'Hải Dương'), ('Nam Sách', 'Hải Dương'), ('Kinh Môn', 'Hải Dương'), ('Kim Thành', 'Hải Dương'), ('Thanh Hà', 'Hải Dương'), ('Cẩm Giàng', 'Hải Dương'), ('Bình Giang', 'Hải Dương'), ('Gia Lộc', 'Hải Dương'), ('Tứ Kỳ', 'Hải Dương'), ('Ninh Giang', 'Hải Dương'), ('Thanh Miện', 'Hải Dương');
INSERT INTO pools_address (district, province_city) VALUES ('Vị Thanh', 'Hậu Giang'), ('Ngã Bảy', 'Hậu Giang'), ('Châu Thành A', 'Hậu Giang'), ('Phụng Hiệp', 'Hậu Giang'), ('Vị Thuỷ', 'Hậu Giang'), ('Long Mỹ', 'Hậu Giang'), ('Long Mỹ', 'Hậu Giang');
INSERT INTO pools_address (district, province_city) VALUES ('Hòa Bình', 'Hòa Bình'), ('Đà Bắc', 'Hòa Bình'), ('Lương Sơn', 'Hòa Bình'), ('Kim Bôi', 'Hòa Bình'), ('Cao Phong', 'Hòa Bình'), ('Tân Lạc', 'Hòa Bình'), ('Mai Châu', 'Hòa Bình'), ('Lạc Sơn', 'Hòa Bình'), ('Yên Thủy', 'Hòa Bình'), ('Lạc Thủy', 'Hòa Bình');
INSERT INTO pools_address (district, province_city) VALUES ('Hưng Yên', 'Hưng Yên'), ('Văn Lâm', 'Hưng Yên'), ('Văn Giang', 'Hưng Yên'), ('Yên Mỹ', 'Hưng Yên'), ('Mỹ Hào', 'Hưng Yên'), ('Ân Thi', 'Hưng Yên'), ('Khoái Châu', 'Hưng Yên'), ('Kim Động', 'Hưng Yên'), ('Tiên Lữ', 'Hưng Yên'), ('Phù Cừ', 'Hưng Yên');
INSERT INTO pools_address (district, province_city) VALUES ('Nha Trang', 'Khánh Hòa'), ('Cam Ranh', 'Khánh Hòa'), ('Cam Lâm', 'Khánh Hòa'), ('Vạn Ninh', 'Khánh Hòa'), ('Ninh Hòa', 'Khánh Hòa'), ('Khánh Vĩnh', 'Khánh Hòa'), ('Diên Khánh', 'Khánh Hòa'), ('Khánh Sơn', 'Khánh Hòa'), ('Trường Sa', 'Khánh Hòa');
INSERT INTO pools_address (district, province_city) VALUES ('Tuyên Quang', 'Tuyên Quang'), ('Lâm Bình', 'Tuyên Quang'), ('Na Hang', 'Tuyên Quang'), ('Chiêm Hóa', 'Tuyên Quang'), ('Hàm Yên', 'Tuyên Quang'), ('Yên Sơn', 'Tuyên Quang'), ('Sơn Dương', 'Tuyên Quang');
INSERT INTO pools_address (district, province_city) VALUES ('Lào Cai', 'Lào Cai'), ('Bát Xát', 'Lào Cai'), ('Mường Khương', 'Lào Cai'), ('Si Ma Cai', 'Lào Cai'), ('Bắc Hà', 'Lào Cai'), ('Bảo Thắng', 'Lào Cai'), ('Bảo Yên', 'Lào Cai'), ('Sa Pa', 'Lào Cai'), ('Văn Bàn', 'Lào Cai');
INSERT INTO pools_address (district, province_city) VALUES ('Điện Biên Phủ', 'Điện Biên'), ('Mường Lay', 'Điện Biên'), ('Mường Nhé', 'Điện Biên'), ('Mường Chà', 'Điện Biên'), ('Tủa Chùa', 'Điện Biên'), ('Tuần Giáo', 'Điện Biên'), ('Điện Biên', 'Điện Biên'), ('Điện Biên Đông', 'Điện Biên'), ('Mường Ảng', 'Điện Biên'), ('Nậm Pồ', 'Điện Biên');
INSERT INTO pools_address (district, province_city) VALUES ('Lai Châu', 'Lai Châu'), ('Tam Đường', 'Lai Châu'), ('Mường Tè', 'Lai Châu'), ('Sìn Hồ', 'Lai Châu'), ('Phong Thổ', 'Lai Châu'), ('Than Uyên', 'Lai Châu'), ('Tân Uyên', 'Lai Châu'), ('Nậm Nhùn', 'Lai Châu');
INSERT INTO pools_address (district, province_city) VALUES ('Sơn La', 'Sơn La'), ('Quỳnh Nhai', 'Sơn La'), ('Thuận Châu', 'Sơn La'), ('Mường La', 'Sơn La'), ('Bắc Yên', 'Sơn La'), ('Phù Yên', 'Sơn La'), ('Mộc Châu', 'Sơn La'), ('Yên Châu', 'Sơn La'), ('Mai Sơn', 'Sơn La'), ('Sông Mã', 'Sơn La'), ('Sốp Cộp', 'Sơn La'), ('Vân Hồ', 'Sơn La');
INSERT INTO pools_address (district, province_city) VALUES ('Yên Bái', 'Yên Bái'), ('Nghĩa Lộ', 'Yên Bái'), ('Lục Yên', 'Yên Bái'), ('Văn Yên', 'Yên Bái'), ('Mù Căng Chải', 'Yên Bái'), ('Trấn Yên', 'Yên Bái'), ('Trạm Tấu', 'Yên Bái'), ('Văn Chấn', 'Yên Bái'), ('Yên Bình', 'Yên Bái');
INSERT INTO pools_address (district, province_city) VALUES ('Thái Nguyên', 'Thái Nguyên'), ('Sông Công', 'Thái Nguyên'), ('Định Hóa', 'Thái Nguyên'), ('Phú Lương', 'Thái Nguyên'), ('Đồng Hỷ', 'Thái Nguyên'), ('Võ Nhai', 'Thái Nguyên'), ('Đại Từ', 'Thái Nguyên'), ('Phổ Yên', 'Thái Nguyên'), ('Phú Bình', 'Thái Nguyên');
INSERT INTO pools_address (district, province_city) VALUES ('Lạng Sơn', 'Lạng Sơn'), ('Tràng Định', 'Lạng Sơn'), ('Bình Gia', 'Lạng Sơn'), ('Văn Lãng', 'Lạng Sơn'), ('Cao Lộc', 'Lạng Sơn'), ('Văn Quan', 'Lạng Sơn'), ('Bắc Sơn', 'Lạng Sơn'), ('Hữu Lũng', 'Lạng Sơn'), ('Chi Lăng', 'Lạng Sơn'), ('Lộc Bình', 'Lạng Sơn'), ('Đình Lập', 'Lạng Sơn');
INSERT INTO pools_address (district, province_city) VALUES ('Hạ Long', 'Quảng Ninh'), ('Móng Cái', 'Quảng Ninh'), ('Cẩm Phả', 'Quảng Ninh'), ('Uông Bí', 'Quảng Ninh'), ('Bình Liêu', 'Quảng Ninh'), ('Tiên Yên', 'Quảng Ninh'), ('Đầm Hà', 'Quảng Ninh'), ('Hải Hà', 'Quảng Ninh'), ('Ba Chẽ', 'Quảng Ninh'), ('Vân Đồn', 'Quảng Ninh'), ('Đông Triều', 'Quảng Ninh'), ('Quảng Yên', 'Quảng Ninh'), ('Cô Tô', 'Quảng Ninh');
INSERT INTO pools_address (district, province_city) VALUES ('Việt Trì', 'Phú Thọ'), ('Phú Thọ', 'Phú Thọ'), ('Đoan Hùng', 'Phú Thọ'), ('Hạ Hoà', 'Phú Thọ'), ('Thanh Ba', 'Phú Thọ'), ('Phù Ninh', 'Phú Thọ'), ('Yên Lập', 'Phú Thọ'), ('Cẩm Khê', 'Phú Thọ'), ('Tam Nông', 'Phú Thọ'), ('Lâm Thao', 'Phú Thọ'), ('Thanh Sơn', 'Phú Thọ'), ('Thanh Thuỷ', 'Phú Thọ'), ('Tân Sơn', 'Phú Thọ');
INSERT INTO pools_address (district, province_city) VALUES ('Vĩnh Yên', 'Vĩnh Phúc'), ('Phúc Yên', 'Vĩnh Phúc'), ('Lập Thạch', 'Vĩnh Phúc'), ('Tam Dương', 'Vĩnh Phúc'), ('Tam Đảo', 'Vĩnh Phúc'), ('Bình Xuyên', 'Vĩnh Phúc'), ('Yên Lạc', 'Vĩnh Phúc'), ('Vĩnh Tường', 'Vĩnh Phúc'), ('Sông Lô', 'Vĩnh Phúc');
INSERT INTO pools_address (district, province_city) VALUES ('Thái Bình', 'Thái Bình'), ('Quỳnh Phụ', 'Thái Bình'), ('Hưng Hà', 'Thái Bình'), ('Đông Hưng', 'Thái Bình'), ('Thái Thụy', 'Thái Bình'), ('Tiền Hải', 'Thái Bình'), ('Kiến Xương', 'Thái Bình'), ('Vũ Thư', 'Thái Bình');
INSERT INTO pools_address (district, province_city) VALUES ('Nam Định', 'Nam Định'), ('Mỹ Lộc', 'Nam Định'), ('Vụ Bản', 'Nam Định'), ('Ý Yên', 'Nam Định'), ('Nghĩa Hưng', 'Nam Định'), ('Nam Trực', 'Nam Định'), ('Trực Ninh', 'Nam Định'), ('Xuân Trường', 'Nam Định'), ('Giao Thủy', 'Nam Định'), ('Hải Hậu', 'Nam Định');
INSERT INTO pools_address (district, province_city) VALUES ('Ninh Bình', 'Ninh Bình'), ('Tam Điệp', 'Ninh Bình'), ('Nho Quan', 'Ninh Bình'), ('Gia Viễn', 'Ninh Bình'), ('Hoa Lư', 'Ninh Bình'), ('Yên Khánh', 'Ninh Bình'), ('Kim Sơn', 'Ninh Bình'), ('Yên Mô', 'Ninh Bình');
INSERT INTO pools_address (district, province_city) VALUES ('Thanh Hóa', 'Thanh Hóa'), ('Bỉm Sơn', 'Thanh Hóa'), ('Sầm Sơn', 'Thanh Hóa'), ('Mường Lát', 'Thanh Hóa'), ('Quan Hóa', 'Thanh Hóa'), ('Bá Thước', 'Thanh Hóa'), ('Quan Sơn', 'Thanh Hóa'), ('Lang Chánh', 'Thanh Hóa'), ('Ngọc Lặc', 'Thanh Hóa'), ('Cẩm Thủy', 'Thanh Hóa'), ('Thạch Thành', 'Thanh Hóa'), ('Hà Trung', 'Thanh Hóa'), ('Vĩnh Lộc', 'Thanh Hóa'), ('Yên Định', 'Thanh Hóa'), ('Thọ Xuân', 'Thanh Hóa'), ('Thường Xuân', 'Thanh Hóa'), ('Triệu Sơn', 'Thanh Hóa'), ('Thiệu Hóa', 'Thanh Hóa'), ('Hoằng Hóa', 'Thanh Hóa'), ('Hậu Lộc', 'Thanh Hóa'), ('Nga Sơn', 'Thanh Hóa'), ('Như Xuân', 'Thanh Hóa'), ('Như Thanh', 'Thanh Hóa'), ('Nông Cống', 'Thanh Hóa'), ('Đông Sơn', 'Thanh Hóa'), ('Quảng Xương', 'Thanh Hóa'), ('Nghi Sơn', 'Thanh Hóa');
INSERT INTO pools_address (district, province_city) VALUES ('Vinh', 'Nghệ An'), ('Cửa Lò', 'Nghệ An'), ('Thái Hoà', 'Nghệ An'), ('Quế Phong', 'Nghệ An'), ('Quỳ Châu', 'Nghệ An'), ('Kỳ Sơn', 'Nghệ An'), ('Tương Dương', 'Nghệ An'), ('Nghĩa Đàn', 'Nghệ An'), ('Quỳ Hợp', 'Nghệ An'), ('Quỳnh Lưu', 'Nghệ An'), ('Con Cuông', 'Nghệ An'), ('Tân Kỳ', 'Nghệ An'), ('Anh Sơn', 'Nghệ An'), ('Diễn Châu', 'Nghệ An'), ('Yên Thành', 'Nghệ An'), ('Đô Lương', 'Nghệ An'), ('Thanh Chương', 'Nghệ An'), ('Nghi Lộc', 'Nghệ An'), ('Nam Đàn', 'Nghệ An'), ('Hưng Nguyên', 'Nghệ An'), ('Hoàng Mai', 'Nghệ An');
INSERT INTO pools_address (district, province_city) VALUES ('Đồng Hới', 'Quảng Bình'), ('Minh Hóa', 'Quảng Bình'), ('Tuyên Hóa', 'Quảng Bình'), ('Quảng Trạch', 'Quảng Bình'), ('Bố Trạch', 'Quảng Bình'), ('Quảng Ninh', 'Quảng Bình'), ('Lệ Thủy', 'Quảng Bình'), ('Ba Đồn', 'Quảng Bình');
INSERT INTO pools_address (district, province_city) VALUES ('Đông Hà', 'Quảng Trị'), ('Quảng Trị', 'Quảng Trị'), ('Vĩnh Linh', 'Quảng Trị'), ('Hướng Hóa', 'Quảng Trị'), ('Gio Linh', 'Quảng Trị'), ('Đa Krông', 'Quảng Trị'), ('Cam Lộ', 'Quảng Trị'), ('Triệu Phong', 'Quảng Trị'), ('Hải Lăng', 'Quảng Trị'), ('Cồn Cỏ', 'Quảng Trị');
INSERT INTO pools_address (district, province_city) VALUES ('Huế', 'Thừa Thiên Huế'), ('Phong Điền', 'Thừa Thiên Huế'), ('Quảng Điền', 'Thừa Thiên Huế'), ('Phú Vang', 'Thừa Thiên Huế'), ('Hương Thủy', 'Thừa Thiên Huế'), ('Hương Trà', 'Thừa Thiên Huế'), ('A Lưới', 'Thừa Thiên Huế'), ('Phú Lộc', 'Thừa Thiên Huế'), ('Nam Đông', 'Thừa Thiên Huế');
INSERT INTO pools_address (district, province_city) VALUES ('Tam Kỳ', 'Quảng Nam'), ('Hội An', 'Quảng Nam'), ('Tây Giang', 'Quảng Nam'), ('Đông Giang', 'Quảng Nam'), ('Đại Lộc', 'Quảng Nam'), ('Điện Bàn', 'Quảng Nam'), ('Duy Xuyên', 'Quảng Nam'), ('Quế Sơn', 'Quảng Nam'), ('Nam Giang', 'Quảng Nam'), ('Phước Sơn', 'Quảng Nam'), ('Hiệp Đức', 'Quảng Nam'), ('Thăng Bình', 'Quảng Nam'), ('Tiên Phước', 'Quảng Nam'), ('Bắc Trà My', 'Quảng Nam'), ('Nam Trà My', 'Quảng Nam'), ('Núi Thành', 'Quảng Nam'), ('Phú Ninh', 'Quảng Nam'), ('Nông Sơn', 'Quảng Nam');

INSERT INTO pools_address (district, province_city) VALUES 
('Quảng Ngãi', 'Quảng Ngãi'),('Bình Sơn', 'Quảng Ngãi'),('Trà Bồng', 'Quảng Ngãi'),('Sơn Tịnh', 'Quảng Ngãi'),('Tư Nghĩa', 'Quảng Ngãi'),('Sơn Hà', 'Quảng Ngãi'),('Sơn Tây', 'Quảng Ngãi'),('Minh Long', 'Quảng Ngãi'),('Nghĩa Hành', 'Quảng Ngãi'),('Mộ Đức', 'Quảng Ngãi'),('Đức Phổ', 'Quảng Ngãi'),('Ba Tơ', 'Quảng Ngãi'),('Lý Sơn', 'Quảng Ngãi'),
('Tuy Hoà', 'Phú Yên'),('Sông Cầu', 'Phú Yên'),('Đồng Xuân', 'Phú Yên'),('Tuy An', 'Phú Yên'),('Sơn Hòa', 'Phú Yên'),('Sông Hinh', 'Phú Yên'),('Tây Hoà', 'Phú Yên'),('Phú Hoà', 'Phú Yên'),('Đông Hòa', 'Phú Yên'),
('Phan Rang-Tháp Chàm', 'Ninh Thuận'),('Bác Ái', 'Ninh Thuận'),('Ninh Sơn', 'Ninh Thuận'),('Ninh Hải', 'Ninh Thuận'),('Ninh Phước', 'Ninh Thuận'),('Thuận Bắc', 'Ninh Thuận'),('Thuận Nam', 'Ninh Thuận'),
('Kon Tum', 'Kon Tum'),('Đắk Glei', 'Kon Tum'),('Ngọc Hồi', 'Kon Tum'),('Đắk Tô', 'Kon Tum'),('Kon Plông', 'Kon Tum'),('Kon Rẫy', 'Kon Tum'),('Đắk Hà', 'Kon Tum'),('Sa Thầy', 'Kon Tum'),('Tu Mơ Rông', 'Kon Tum'),('Ia H\' Drai', 'Kon Tum'),
('Bạc Liêu', 'Bạc Liêu'),('Hồng Dân', 'Bạc Liêu'),('Phước Long', 'Bạc Liêu'),('Vĩnh Lợi', 'Bạc Liêu'),('Giá Rai', 'Bạc Liêu'),('Đông Hải', 'Bạc Liêu'),('Hoà Bình', 'Bạc Liêu'),
('Đà Lạt', 'Lâm Đồng'),('Bảo Lộc', 'Lâm Đồng'),('Đam Rông', 'Lâm Đồng'),('Lạc Dương', 'Lâm Đồng'),('Lâm Hà', 'Lâm Đồng'),('Đơn Dương', 'Lâm Đồng'),('Đức Trọng', 'Lâm Đồng'),('Di Linh', 'Lâm Đồng'),('Đạ Huoai', 'Lâm Đồng'),('Đạ Tẻh', 'Lâm Đồng'),('Cát Tiên', 'Lâm Đồng'),
('Tây Ninh', 'Tây Ninh'),('Tân Biên', 'Tây Ninh'),('Tân Châu', 'Tây Ninh'),('Dương Minh Châu', 'Tây Ninh'),('Châu Thành', 'Tây Ninh'),('Hòa Thành', 'Tây Ninh'),('Gò Dầu', 'Tây Ninh'),('Bến Cầu', 'Tây Ninh'),('Trảng Bàng', 'Tây Ninh'),
('Tân An', 'Long An'),('Kiến Tường', 'Long An'),('Tân Hưng', 'Long An'),('Vĩnh Hưng', 'Long An'),('Mộc Hóa', 'Long An'),('Tân Thạnh', 'Long An'),('Thạnh Hóa', 'Long An'),('Đức Huệ', 'Long An'),('Đức Hòa', 'Long An'),('Bến Lức', 'Long An'),('Thủ Thừa', 'Long An'),('Tân Trụ', 'Long An'),('Cần Đước', 'Long An'),('Cần Giuộc', 'Long An'),
('Mỹ Tho', 'Tiền Giang'),('Gò Công', 'Tiền Giang'),('Cai Lậy', 'Tiền Giang'),('Tân Phước', 'Tiền Giang'),('Cái Bè', 'Tiền Giang'),('Chợ Gạo', 'Tiền Giang'),('Gò Công Tây', 'Tiền Giang'),('Gò Công Đông', 'Tiền Giang'),('Tân Phú Đông', 'Tiền Giang'),
('Trà Vinh', 'Trà Vinh'),('Càng Long', 'Trà Vinh'),('Cầu Kè', 'Trà Vinh'),('Tiểu Cần', 'Trà Vinh'),('Cầu Ngang', 'Trà Vinh'),('Trà Cú', 'Trà Vinh'),('Duyên Hải', 'Trà Vinh'),('Duyên Hải', 'Trà Vinh'),
('Vĩnh Long', 'Vĩnh Long'),('Long Hồ', 'Vĩnh Long'),('Mang Thít', 'Vĩnh Long'),('Vũng Liêm', 'Vĩnh Long'),('Tam Bình', 'Vĩnh Long'),('Bình Minh', 'Vĩnh Long'),('Trà Ôn', 'Vĩnh Long'),('Bình Tân', 'Vĩnh Long'),
('Rạch Giá', 'Kiên Giang'),('Hà Tiên', 'Kiên Giang'),('Kiên Lương', 'Kiên Giang'),('Hòn Đất', 'Kiên Giang'),('Tân Hiệp', 'Kiên Giang'),('Giồng Riềng', 'Kiên Giang'),('Gò Quao', 'Kiên Giang'),('An Biên', 'Kiên Giang'),('An Minh', 'Kiên Giang'),('Vĩnh Thuận', 'Kiên Giang'),('Phú Quốc', 'Kiên Giang'),('Kiên Hải', 'Kiên Giang'),('U Minh Thượng', 'Kiên Giang'),('Giang Thành', 'Kiên Giang');

